baseURL = 'https://snegovikufa.github.io/cyprusrockseu/'
languageCode = 'en-us'
title = 'Cyprus Rock Climbing'
theme = 'blist'
description = "an online guide to Rock Climbing on the Mediterranean island of Cyprus"
canonifyURLs = true

[author]
  name = "Rustam Safin"
  homepage = "https://snegovikufa.github.io/cyprusrockseu/"

[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"

    [languages.en.params]
      introTitle = "Welcome to Cyprus"
      introSubtitle = "Welcome to CyprusRocks - an online guide to Rock Climbing on the Mediterranean island of Cyprus. Cyprus is one of the largest islands in the med and has the best weather in Europe. While relatively unknown as a climbing destination, the number, quality, and diversity of routes belies its low key reputation. Hard information supplying details of the climbing on offer has traditionally been difficult to track down. This web-site attempts to address this. Enjoy!"
      introPhoto = "/main.jpg"
      logo = "/cyprus.png"
    [[languages.en.menu.main]]
        name = "Lead Climbing"
        url = "/areas/climbing-areas"
        weight = 1

    [[languages.en.menu.main]]
        name = "Bouldering"
        url = "/areas/bouldering-sectors/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Deep Water Solo"
        url = "/areas/dws-sectors"
        weight = 3

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = false
  
  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright © 2023 - Cyprus Rocks · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-yellow-300"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

# Comments system
[params.comments]
  # Supports disqus, giscus and utterances
  # Check hugo docs for setting up disqus
  system = "giscus"

  # Options for giscus, exclude hyphens
  repo = ""
  repoid = ""
  category = ""
  categoryid = ""
  mapping = ""
  strict = ""
  reactionsenabled = ""
  emitmetadata = ""
  inputposition = ""
  theme = ""

  # Options for utterances, exclude hyphens
  # repo = ""
  # issueterm = ""
  # theme = ""

[params.homepage.social]
  # Global params common for both languages
  title = "Social media"
  description = "Feel free to tag us and share memes"

  [[params.homepage.social.icons]]
    website = "instagram"
    url = "https://www.instagram.com/cyprusoutdoors/"
  [[params.homepage.social.icons]]
    website = "facebook"
    url = "https://www.facebook.com/groups/9963959894"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
